#
# /etc/rawm/rawmstat.conf: rawm status producer configuration
#

status = {
  protocol = "rawm-v2";
};

blocks = (
  {
    name = "clock";
    command = ("date", "+%a %b %d %H:%M");
    interval = 5;
    signal = 0;
    timeout_ms = 2000;
  }
);
